#!/usr/bin/env bash
# This script configures a new Ubuntu machine to install and configure Nginx.

printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
