#!/usr/bin/env bash
# A Bash script that displays Best School 10 times but Hi on the 9th.

i=0
while [ $i -le 20 ]
do

	case $i in

	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	*)
                echo $i
		;;
	esac
	((i++))
done
