#!/usr/bin/env bash
# A Bash script that displays Best School 10 times but Hi on the 9th.

i=1
while [ $i -le 21 ]
do
	echo $i
	case $i in

	4) 
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	((i++))
done
